### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by TheLortex** [VengeurK/PINT#2]
https://github.com/VengeurK/PINT/blob/405d3f8df4461721d8fa659fdee7e1e0ea0959cc/src/ts/tools/autoselectTool.ts#L3

The controller shouldn't be referred to as a global (this breaks the tests, thus the build).
I think the Selection object should be given to every tool, making them able to modify the selection without having access to the whole controller.

**Comment by Marc-Ducret** [comment]
That makes sense, but then we should pass the Project to the tools, because they might want to change many other things than the selection (think, changing the current color or the current tool...).

**Comment by TheLortex** [comment]
A temp fix has been made, giving to every tool the instance of Selection on use.
