### ISSUE TITLE
Saving picture does not work on Firefox

### ISSUE THREAD

**Issue by TheLortex** [VengeurK/PINT#5]
Version: "Mozilla/5.0
(X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

**Comment by Marc-Ducret** [comment]
For now, we should display to Firefox users that only Chrome is officially supported.

**Comment by TheLortex** [comment]
Fixed by commit 23d10ade1fc999e9bb7fb16ead13686a000ac77e
